version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./src:/var/www/html

  # Facultatif : base de données
  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: motdepasse
  #     MYSQL_DATABASE: nomdb
  #     MYSQL_USER: utilisateur
  #     MYSQL_PASSWORD: motdepasse
