version: '3.8'

services:
  monsite-php:
    image: php:8.2-apache
    container_name: korra
    volumes:
      - ./src:/var/www/html
    environment:
      - VIRTUAL_HOST=korra.dev,www.korra.dev
      - LETSENCRYPT_HOST=korra.dev,www.korra.dev
      - LETSENCRYPT_EMAIL=admin@korra.dev
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
