version: '3.8'

services:
  monsite-php:
    image: php:8.2-apache
    container_name: korra
    volumes:
      - ./www:/var/www/html
    environment:
      - VIRTUAL_HOST=www.korra.dev
      - LETSENCRYPT_HOST=www.korra.dev
      - LETSENCRYPT_EMAIL=admin@korra.dev
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true

    
  # Facultatif : base de données
  # db:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: motdepasse
  #     MYSQL_DATABASE: nomdb
  #     MYSQL_USER: utilisateur
  #     MYSQL_PASSWORD: motdepasse
